### ISSUE TITLE
Xin giải đáp các file trong web.

### ISSUE THREAD

**Issue by hythang2020** [chungpv-1008/GreatKart#1]
Xin chào ! Mình có xem file của bạn trên github cũng như file hướng dẫn ở trang 2kvn.Bài viết của bạn khá hay nên mình muốn học làm theo . khi xem đến phần tạo views cho store mình hiểu cách bạn gọi category lên template navbar,store như thế nào ? trong file bạn dùng for category in links . Links thì bạn tạo dict trong file context. Mà trong file store/views.py bạn không xuất ra context. Mình mới tìm hiểu mong bạn hướng dẫn giúp mình. Thanks.

**Comment by chungpv-1008** [comment]
Chào bạn,
Như bạn thấy trong file [template/includes/navbar.html](https://github.com/chungpv-1008/GreatKart/blob/master/templates/includes/navbar.html) mình có dùng `links`, có rất nhiều file include file navbar này, nghĩa là có rất nhiều template gọi đến biến đó, mình không thể khai báo 1 context dùng nhiều lần ở tất cả các views.py mà nó cần được. Mình đã dùng đến `context_processors`, ở dòng [này](https://github.com/chungpv-1008/GreatKart/blob/5b97d04be4bdf1ad82eccab9ab0d43f6aac07852/greatkart/settings.py#L58) và khai báo ở file [này](https://github.com/chungpv-1008/GreatKart/blob/master/category/context_processors.py). Mình cũng dùng tương tự với biến `counter`.
Làm như vậy thì tất cả các file template đều gọi được mà không cần khai báo ở 1 views.py cụ thể nào nữa, nên file `store/store.html` cũng sẽ gọi được.
Trong bài viết Viblo mình cũng nói sơ qua phần [này](https://viblo.asia/p/de-dang-co-ngay-ung-dung-e-commerce-voi-django-part-2-aWj53n2Yl6m#_context-processor-cho-gio-hang-4), bạn có thể tìm hiểu thêm về `context_processors` [ở đây](https://docs.djangoproject.com/en/3.2/ref/templates/api/) nhé :smile: :smile:

**Comment by hythang2020** [comment]
cảm ơn giải đáp rất nhiệt tình của bạn, mình đã hiểu hơn khi nhận được giải thích của bạn. Thanks.
